version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:tools-deps-1.10.0.442
      
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "deps.edn" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-
        
      - run: ./script/cibuild

      - save_cache:
          paths:
            - ~/.m2
            - .cpcache
          key: v2-dependencies-{{ checksum "deps.edn" }}

      - add_ssh_keys:
          fingerprints:
            - "2f:a6:6e:c0:6c:52:4c:44:cf:aa:b1:91:b9:ab:3b:0a"

      - deploy:
          name: deploy to hosting
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh-keyscan -H grumpy.website >> ~/.ssh/known_hosts
              scp target/grumpy.jar grumpy@grumpy.website:
              ssh grumpy@grumpy.website /home/grumpy/restart.sh
            fi